### ISSUE TITLE
为何内存一直快速增长？是否有默认占内存的配置

### ISSUE THREAD

**Issue by quqiufeng** [xelabs/tokudb#10]
my.cnf 如下   16核 16G的内存  两天内存就耗光

[client]

port		= 3306
socket		= /tmp/mysql.sock

[mysqld]
port		= 3306
socket		= /tmp/mysql.sock
skip-external-locking
max_allowed_packet = 12M
table_open_cache = 512
sort_buffer_size = 8M
read_buffer_size = 8M
read_rnd_buffer_size = 8M
myisam_sort_buffer_size = 64M
thread_cache_size = 8 
log-bin=mysql-bin
server-id	= 1
log-bin=mysql-bin

binlog_format=row

open_files_limit = 65535
innodb_open_files=65535
default-storage-engine=InnoDB
thread_handling=pool-of-threads
innodb_buffer_pool_size=500M
innodb_file_per_table = 1
innodb_data_file_path = ibdata1:1G:autoextend
innodb_log_file_size=12M
innodb_log_files_in_group=2
innodb_flush_method = O_DIRECT
innodb_flush_log_at_trx_commit  = 2
innodb_write_io_threads=4
innodb_adaptive_flushing=ON
innodb_change_buffering=all
innodb_stats_on_metadata=OFF

slow_query_log=1
slow_query_log_file=/data/log/mysql/log-slow-queries.log
long_query_time=2
log_queries_not_using_indexes = ON

query_cache_type=0
query_cache_size=0
tokudb_cache_size=100M

sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
explicit_defaults_for_timestamp
[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash

[myisamchk]
key_buffer_size = 32M
sort_buffer_size = 16M
read_buffer = 2M
write_buffer = 2M

[mysqlhotcopy]
interactive-timeout

tokudb_commit_sync=ON
tokudb_fsync_log_period=1000

**Comment by bohutang** [comment]
@quqiufeng 

从你的配置看，分配给innodb/tokudb都很小，不会产生这种问题。
需要确认下执行的什么sql，以及你说的耗光的证据
